<?php

	function create_custom_fields(){
		if( function_exists('acf_add_local_field_group') ):

			acf_add_local_field_group(array (
				'key' => 'group_55f981bf56613',
				'title' => 'Agenda',
				'fields' => array (
					array (
						'key' => 'field_55f981c420c41',
						'label' => 'Datum',
						'name' => 'date',
						'type' => 'date_picker',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'display_format' => 'd/m/Y',
						'return_format' => 'd/m/Y',
						'first_day' => 1,
					),
					array (
						'key' => 'field_55f981e820c42',
						'label' => 'Start tijd',
						'name' => 'start',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '20:00',
						'prepend' => '',
						'append' => 'uur',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_55f9821d20c43',
						'label' => 'Eind tijd',
						'name' => 'end',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '23:00',
						'prepend' => '',
						'append' => 'uur',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
				'location' => array (
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'agenda',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'side',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));

			acf_add_local_field_group(array (
				'key' => 'group_55f9690c45fb1',
				'title' => 'Pagina caroussel',
				'fields' => array (
					array (
						'key' => 'field_55f9690c4cac5',
						'label' => '',
						'name' => 'caroussel',
						'type' => 'repeater',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'min' => '',
						'max' => '',
						'layout' => 'table',
						'button_label' => 'Nieuwe slide toevoegen',
						'sub_fields' => array (
							array (
								'key' => 'field_55f9690c4f942',
								'label' => 'Afbeelding',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'object',
								'preview_size' => 'slideshow',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array (
								'key' => 'field_55f9690c4f980',
								'label' => 'Ondertitel',
								'name' => 'tagline1',
								'type' => 'text',
								'instructions' => '',
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'Jouw inzet wordt gezien',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'readonly' => 0,
								'disabled' => 0,
							),
							array (
								'key' => 'field_55f9690c4f9ab',
								'label' => 'Ondertitel',
								'name' => 'tagline2',
								'type' => 'text',
								'instructions' => '',
								'conditional_logic' => 0,
								'wrapper' => array (
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => 'Daar werken we aan',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
								'readonly' => 0,
								'disabled' => 0,
							),
						),
					),
				),
				'location' => array (
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'nieuws',
						),
					),
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'facts',
						),
					),
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'agenda',
						),
					),
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'page',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));

			acf_add_local_field_group(array (
				'key' => 'group_5d5f981bf56613',
				'title' => 'Links',
				'fields' => array (
					array (
						'key' => 'field_55df981c420c41',
						'label' => 'Link URL',
						'name' => 'text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'key' => 'field_55fs981e820c42',
						'label' => 'Link',
						'name' => 'Link',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'prepend' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
				'location' => array (
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'links',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'side',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));


			acf_add_local_field_group(array (
				'key' => 'group_5603e9fe0cece',
				'title' => 'User Login',
				'fields' => array (
					array (
						'key' => 'field_5603ea0931fe4',
						'label' => 'E-mailadres',
						'name' => 'email',
						'type' => 'email',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Vul in',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_5603ea1631fe5',
						'label' => 'Wachtwoord',
						'name' => 'password',
						'type' => 'password',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'placeholder' => 'Vul in',
						'prepend' => '',
						'append' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
				'location' => array (
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'post',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));

			$required = !current_user_can('edit_others_pages');
			acf_add_local_field_group(array (
				'key' => 'group_5602786b20c8e',
				'title' => 'User Profile',
				'fields' => array (
					array (
						'key' => 'field_560a7f0373254',
						'label' => 'Uw profiel foto',
						'name' => 'avatar',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => 'jpeg, jpg, png, gif',
					),
					array (
						'key' => 'field_5603ca2b0fdd2',
						'label' => 'Naam',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Voeg toe',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_56029b807ab8b',
						'label' => 'Functie',
						'name' => 'function',
						'type' => 'text',
						'instructions' => '',
						'required' => $required,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Voeg toe',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_5602788536a3a',
						'label' => 'Telefoon',
						'name' => 'phone',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Voeg toe',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_5603cc04fd5fb',
						'label' => 'E-mailadres',
						'name' => 'email',
						'type' => 'email',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Voeg toe',
						'prepend' => '',
						'append' => '',
					),
					array (
						'key' => 'field_56028bb8b2420',
						'label' => 'Bedrijfsnaam',
						'name' => 'company',
						'type' => 'text',
						'instructions' => '',
						'required' => $required,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Voeg toe',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_58b246028bb20',
						'label' => 'Bedrijfs URL',
						'name' => 'company_url',
						'type' => 'url',
						'instructions' => '',
						'required' => $required,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
					array (
						'key' => 'field_56027c7436a3c',
						'label' => 'Bedrijfsadres',
						'name' => 'location',
						'type' => 'google_map',
						'instructions' => '',
						'required' => $required,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'center_lat' => '52.5142306',
						'center_lng' => '6.1069978',
						'zoom' => 12,
						'height' => '',
					),
					array (
						'key' => 'field_56027c2b36a3b',
						'label' => 'Specialisme',
						'name' => 'field',
						'type' => 'checkbox',
						'instructions' => '',
						'required' => $required,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array (
							'Werkgevers' => 'Werkgevers',
							'Werkzoekenden' => 'Werkzoekenden',
							'Doelgroep garantiebanen' => 'Doelgroep garantiebanen',
							'Jeugd' => 'Jeugd',
							'Leren en werken' => 'Leren en werken',
							'Ontwikkeling & opleiding' => 'Ontwikkeling & opleiding',
							'Basisset instrumenten' => 'Basisset instrumenten',
							'Loonwaardebepaling' => 'Loonwaardebepaling',
							'Communicatie' => 'Communicatie',
							'Overig' => 'Overig',
						),
						'default_value' => array (
						),
						'allow_null' => 0,
						'multiple' => 1,
						'ui' => 0,
						'ajax' => 0,
						'placeholder' => '',
						'disabled' => 0,
						'readonly' => 0,
					),
					array (
						'key' => 'field_5603ca370fdd3',
						'label' => 'Motto',
						'name' => 'motto',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Voeg toe',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => 0,
						'disabled' => 0,
					),
				),
				'location' => array (
					array (
						array (
							'param' => 'user_form',
							'operator' => '==',
							'value' => 'edit',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));

			acf_add_local_field_group(array (
				'key' => 'group_5602aa805fd34',
				'title' => 'User Registration',
				'fields' => array (
					array (
						'key' => 'field_5602aa86b3cbd',
						'label' => 'E-mailadres',
						'name' => 'email',
						'type' => 'email',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Vul in',
						'prepend' => '',
						'append' => '',
					),
				),
				'location' => array (
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'post',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));


			/**
			 * Password reset
			 */
			acf_add_local_field_group(array (
				'key' => 'group_5628f44c56ca2',
				'title' => 'User Password',
				'fields' => array (
					array (
						'key' => 'field_5628f44c5da82',
						'label' => 'E-mailadres',
						'name' => 'email',
						'type' => 'email',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => 'Vul in',
						'prepend' => '',
						'append' => '',
					),
				),
				'location' => array (
					array (
						array (
							'param' => 'post_type',
							'operator' => '==',
							'value' => 'post',
						),
					),
				),
				'menu_order' => 0,
				'position' => 'normal',
				'style' => 'default',
				'label_placement' => 'top',
				'instruction_placement' => 'label',
				'hide_on_screen' => '',
				'active' => 1,
				'description' => '',
			));

		endif;
	}

	add_action('init', 'create_custom_fields');


	add_filter( 'wpmu_signup_user_notification', '__return_false' ); // Disable confirmation email
	add_filter( 'wpmu_welcome_user_notification', '__return_false' ); // Disable welcome email
